version: '3'
services:
 my-postgres:
   image: postgres
   restart: always
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=93773621
     - POSTGRES_DB=forum
   networks:
     - forum
   volumes:
     - ../data :/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4
#    ports:
#      - "5050:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    networks:
#      - forum

 backend:
  image: anniexp/forum-backend:latest
  ports:
     - "8081:8081"
  depends_on:
     - my-postgres
  networks:
     - forum

 frontend:
   image: anniexp/forum-frontend:latest
   ports:
     - "3000:3000"
   networks:
     - forum
   depends_on:
     - backend

 watchtower:
   image: containrrr/watchtower
   volumes:
     - ../wachtower:/var/run/docker.sock
   command: --monitor-only backend frontend --interval 86400

networks:
 forum:
