name: CI
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    # - name: Build and push
    #   uses: docker/build-push-action@v4
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest

    - name: Redicrect to docker-compose file
      run: cd ../../
    - name: Docker Compose Action
      run: docker compose up -d
      # uses: isbang/compose-action@v1.4.1
      # with:
      #   compose-file: ../../docker-compose.yml
      #   down-flags: "--volumes"
        # services: |
        #   my-postgres
        #   backend
        #   frontend
    - name: Test
      run: docker run --network container:forum-dockerized-frontend-1 anniexp/forum-frontend:latest http://localhost:3000/
    - run: curl localhost